### ISSUE TITLE
Invalid video file for mkv

### ISSUE THREAD

**Issue by azizLIGHT** [NDVM/NDVM#17]
I'm getting error messages saying my files are invalid video files, when I ran start.sh -d on Ubuntu 14.04 x64 with nodejs 0.10.25~dfsg
It seems to be saying all video files are invalid, so far I've tried mkv, mp4, and flv

I checked server/utils/walker.js and on line 20 I can see all my file types are listed there that I tested, so I'm not sure what's going on

**Comment by hlechner** [comment]
Seems that you're having problem with ffprobe check.

Could you please test to change the walker.js for this old version (before ffprobe test being implemented)
https://github.com/NDVM/NDVM/blob/d86d188ccbaec146a54259a75a82ddc73e7c4e4a/server/src/utils/walker.js

And let me know if it works?

**Comment by azizLIGHT** [comment]
I replaced the existing server/utils/walker.js with the one you linked and I got the following error:


```
aziz@fractal:~/Downloads/NDVM-master$ ./start.sh -d
[INFO] "NDVM Debug" enabled
[INFO] Node.JS version: v0.10.25
[OK] Executing NDVM ...
[OK] Node.JS return:


/home/aziz/Downloads/NDVM-master/server/utils/walker.js:7
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/aziz/Downloads/NDVM-master/server/utils/system.js:9:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
aziz@fractal:~/Downloads/NDVM-master$ 
```

**Comment by azizLIGHT** [comment]
Your old walker.js seems to be working. I have been able to add my files to the DB and then click them and have them play in my default media player (I do see that it is having troubles generating thumbnails, I can see spinning circles, but I suppose this is a separate issue)

So I suppose I can close this issue? Or maybe you want to debug further and see what is the cause? I am available for that if you need anything.

**Comment by hlechner** [comment]
We can stay on this issue.


>The NDVM was a process to fix wwidd wich is deprecated right now (not developed by me)
>
>However seems that I faced what the original developer faced to stop the development: the software structure is not very clean and the best approach would be create a new application. So maybe I will try create a new software from scratch using python instead.
>
>The new features are halted by now on NDVM but I can help to make it works.

Could you provide me log/message from the console when running NDVM?

I need to re-check it, but nodejs 0.10 seems a bit outdated to NDVM, maybe the version nodejs 0.12 or even nodejs 4 could have better results on it. I will give some tries and let you know about it.

Please feel free to update this issue

**Comment by hlechner** [comment]
@azizLIGHT do you still using the NDVM?  I need your answer to go further.

I've tested the NDVM on node.js v0.10.25 and I found no issue with the current code on my machine.

You can use the nvm to use a different node.js on your system: https://github.com/creationix/nvm
